// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnZgofL6Hn4DHu0lSDg3qgXT4TnV1Ia9U',
    appId: '1:449561753785:web:e52de5b5757f99ba074368',
    messagingSenderId: '449561753785',
    projectId: 'los-pollos-kings',
    authDomain: 'los-pollos-kings.firebaseapp.com',
    storageBucket: 'los-pollos-kings.appspot.com',
    measurementId: 'G-123SX808K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBxhp-pR1Sil3iXUxpMEBMqXA2JVaR9NE',
    appId: '1:449561753785:android:cba443c7a15de454074368',
    messagingSenderId: '449561753785',
    projectId: 'los-pollos-kings',
    storageBucket: 'los-pollos-kings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMsO9JPBxCBTcwiLXYbnExBQM41297spA',
    appId: '1:449561753785:ios:db0e3695454681bd074368',
    messagingSenderId: '449561753785',
    projectId: 'los-pollos-kings',
    storageBucket: 'los-pollos-kings.appspot.com',
    iosBundleId: 'com.example.ownKingNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMsO9JPBxCBTcwiLXYbnExBQM41297spA',
    appId: '1:449561753785:ios:fb0657619e616bac074368',
    messagingSenderId: '449561753785',
    projectId: 'los-pollos-kings',
    storageBucket: 'los-pollos-kings.appspot.com',
    iosBundleId: 'com.example.ownKingNotes.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnZgofL6Hn4DHu0lSDg3qgXT4TnV1Ia9U',
    appId: '1:449561753785:web:cc1cfda0431ffa8f074368',
    messagingSenderId: '449561753785',
    projectId: 'los-pollos-kings',
    authDomain: 'los-pollos-kings.firebaseapp.com',
    storageBucket: 'los-pollos-kings.appspot.com',
    measurementId: 'G-DS8VLHHWCK',
  );

}